import Head from 'next/head';
import Navbar from '../components/Navbar';
import { Hero } from '../components/Hero';

export default function Home() {
  return (
    <div className='home '>
      <Head>
        <title>Personal Website</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Hero />
    </div>
  );
}
